sudo: false

dist: xenial

before_install:
  - export PATH=$PATH

before_script: true

after_failure: true

after_success: true

after_script: true

script: bash test.sh

matrix:
  include:
    - name: "MMdnn no-onnx test with py2/ubuntu 16.04"
      language: python
      python: "2.7"
      env: TEST_ONNX=false
      install:
        - pip install -q tensorflow==1.8.0
        - pip install -q -r requirements.txt
        - pip install -q http://download.pytorch.org/whl/cpu/torch-0.4.0-cp27-cp27mu-linux_x86_64.whl
        - pip install -q torchvision
        # - pip install -q paddlepaddle==0.11.0

    - name: "MMdnn onnx test with py2/ubuntu 16.04"
      language: python
      python: "2.7"
      env: TEST_ONNX=true
      install:
        - pip install -q tensorflow==1.8.0
        - pip install -q -r requirements.txt
        - pip install -q http://download.pytorch.org/whl/cpu/torch-0.4.0-cp27-cp27mu-linux_x86_64.whl
        - pip install -q torchvision
        # - pip install -q paddlepaddle==0.11.0
        - pip install -q onnx==1.2.1
        - pip install -q onnx-tf==1.1.2

    - name: "MMdnn no-onnx test with py3/ubuntu 16.04"
      language: python
      python: "3.6"
      env: TEST_ONNX=false
      install:
        - pip install -q tensorflow==1.10.0
        - pip install -q -r requirements.txt
        - pip install -q http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
        - pip install -q torchvision

    - name: "MMdnn onnx test with py3/ubuntu 16.04"
      language: python
      python: "3.6"
      env: TEST_ONNX=true
      install:
        - pip install -q tensorflow==1.10.0
        - pip install -q -r requirements.txt
        - pip install -q http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl
        - pip install -q torchvision
        - pip install -q onnx==1.2.1
        - pip install -q onnx-tf==1.1.2
